name = str(input('Digite uma frase')).strip()
a = name.lower()
print(' A letra A aparece {} vezes na frase.'.format(a.count('a')))
print('A letra A apareceu pela primeira vez na posição {}.'.format(a.find('a') + 1))
print('A letra aparece pela última vez na posição {}'.format(a.rfind('a')+ 1))